train test split

In [6]:
from sklearn.model_selection import train_test_split
import numpy as np

x=np.array([[1],[2],[3],[4],[5],[6]])
y=np.array([10,20,30,40,50,60])

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

print("x")
print(x_train)
print(x_test)
print("y")
print(y_train)
print(y_test)

x
[[6]
 [5]
 [2]
 [4]]
[[3]
 [1]]
y
[60 50 20 40]
[30 10]


Model train and test

In [8]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

pre=model.predict(x_test)
print(pre)

[30. 10.]


accuracy and score

In [9]:
score=model.score(x_test,y_test)
print(score)

1.0
